### ISSUE TITLE
Reminiscence engine

### ISSUE THREAD

**Issue by MadHed** [cyxx/dpoly_js#1]
Hi cyxx,
is there a reason that the reminiscence source code is not on github?
I fixed some stuff for MSVC and would like to open a PR.

Thanks

**Comment by cyxx** [comment]
Hi,
I consider the Flashback engine mostly complete, so no real need to have a shared repository.
Feel free to send your changes via email or similar.
Thanks,

**Comment by MadHed** [comment]
Ok, thanks for answering.
I'll do that then.
